### ISSUE TITLE
Related work #1 초안 작성(~30)

### ISSUE THREAD

**Issue by sungmin-net** [sungmin-net/android-mdmClient-courseWork#2]
https://docs.google.com/presentation/d/1VaYUVicdY2k2NWSNDsj5dfq3BXvsxCxQyLg__3_i5fk/edit#slide=id.gef99dd79ef_0_107

상기 슬라이드의 Related work#1을 완성하시고 이슈 닫아주세요.

**Comment by swlim02** [comment]
완료
