### ISSUE TITLE
신규 멤버 개발 환경 구성(~11.05)

### ISSUE THREAD

**Issue by sungmin-net** [sungmin-net/android-mdmClient-courseWork#8]
상원 책임님, 본인의 코드로 앱을 빌드하고 서버를 구동할 수 있는 있는 개발환경을 갖춰주세요.

저랑 경헌씨가 작성한 readme 보시고, 나눠드린 폰으로 프로토타입 데모를 스스로 하실 수 있게 되시면 이슈 닫아주세요.

감사합니다.

**Comment by swlim02** [comment]
ING

**Comment by swlim02** [comment]
완료 하였습니다.
