### ISSUE TITLE
지컴시 팀플 2차 미팅 준비#2 - BT 기반 공공장소 식별 관련(~18)

### ISSUE THREAD

**Issue by sungmin-net** [sungmin-net/android-mdmClient-courseWork#9]
지컴시 팀플 2차 미팅 자료 링크: https://docs.google.com/presentation/d/1ZQtmfJFnhAEan6OTSBZ9jhRxd9ysu-MbqqKq5BHGGT8/edit#slide=id.g10202a5c4e4_1_10

안녕하세요. 임상원 책임님,

단카방에서 나누었듯이, BT 개발 관련 PPT 한장 채우기를 부탁드리려고 합니다.

상기 슬라이드 11page에 계획이나 개발 관련 사항을 반영해주세요.

감사합니다.

**Comment by swlim02** [comment]
Start
-> Ing

**Comment by swlim02** [comment]
Ing 인데 ;; 버튼을 잘못 눌렀어요 죄송합니다. Reopen

**Comment by swlim02** [comment]
Done 
완료하였습니다. ㅎㅎㅎㅎ
